### ISSUE TITLE
Feature Request: Sign in using Salesforce / Experience cloud (as the identity provider) 

### ISSUE THREAD

**Issue by JFoxUK** [qwilio/qwil-salesforce-app#9]
Sign in using Salesforce / Experience cloud (as the identity provider) on Qwil so that JIT provisioning can also take place meaning the client and their experience cloud user is kept in sync and they don't have to be invited or registered but also if they choose to use the Qwil app, they login with Experience Cloud credentials. (Similar offering for advisors, use Salesforce as the SSO/IdP.) 

This would allow for less credential management and swivel charing, improving overall UX and security.

**Comment by shawnchin** [comment]
I'm afraid that's a huge change on the Qwil identity model and is beyond the scope of the SDK itself. 

Closing this issue here, but feel free to discuss further with our rep.

**Comment by JFoxUK** [comment]
The challenge this causes is two fold. 
 
1. The client experience. We don't want the client to have to leave the app, to go and do a new sign up process to just use a feature of our app. 
2. If they happen to already be registered for Qwil, today, the Advisor has no way of knowing their Salesforce User ID to add manually to their Qwil record so the advisor has no way to link the client to Qwil user therefore it wont connect

**Comment by shawnchin** [comment]
Yup, we appreciate that the UserId-based mapping is never going to scale -- this demo app is meant to illustrate the simplest possible Salesforce integration and so does not reflect best-practice for enterprise-scale integrations.

Automating user onboarding and migration is something we should certainly discuss further. Qwil provide System APIs for automatically provisioning the accounts during user onboarding, and several ways the SDK can link users across the two systems. 

I suggest we continue this discussion via the usual channels since the others involved will not be on this thread.

_p.s. thanks for your continued feedback and suggestions. The SDK is still very new and will be improved rapidly, so your insights will certain help with prioritising the development efforts._
